title: "Goと関連技術"
summary: "Goやその関連技術（フレームワーク、ライブラリなど）の知識をまとめています。"
topics: ["Go", "echo", "gorm"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - go_doc
  - go_const_var # 変数、定数
  - go_pointer
  - go_type_primitive # bool, string, int
  - go_type_composite # 配列、スライス、マップ
  - go_struct_func_method_interface # 構造体、関数、メソッド、インターフェース
  - go_control # 制御構文
  - go_error # エラー、パニック
  - go_package_module
  - go_goroutine_channel_context # ゴルーチン、チャネル
  - go_test
  - go_log
  - go_file
  - go_cli_fmt_stdin_stdout
  - go_other_format_data
  - go_http
  - go_db_sql
    # - defined type
    # - functional options pattern
    # - イテレータ 1.23から
  - go_architecture # 設計に関すること
  - go_other # その他
  - echo
  - gorm
